Repository microsoft/vscode-mypy, pull requests merged in 2023-08, with the labels that each got.

#100 Ensure `tool` dir is always on path
  bundled/tool/lsp_server.py
Labels: bug

#101 Update packages
  dev_requirements.txt
  package-lock.json
  package.json
Labels: debt

#103 Update extension version for release
  package-lock.json
  package.json
Labels: no-changelog

#104 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#106 Update settings and tests
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  .gitignore
  .vscode/launch.json
  .vscodeignore
  package-lock.json
  package.json
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/status.ts
  src/common/utilities.ts
  src/common/vscodeapi.ts
  src/test/ts_tests/index.ts
  src/test/ts_tests/runTest.ts
  src/test/ts_tests/tests/common/settings.unit.test.ts
  src/test/ts_tests/tests/common/utilities.unit.test.ts
  tsconfig.json
Labels: debt

#107 Stop using legacy `python.linting.mypyArgs`
  src/common/settings.ts
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: bug

#110 Update packages
  dev_requirements.txt
  package-lock.json
  package.json
Labels: debt

#111 Fix typo in default `mypy` args
  bundled/tool/lsp_server.py
Labels: bug

#112 Fix typo in default `mypy` args
  bundled/tool/lsp_server.py
Labels: bug

#113 Update version for recovery release
  package-lock.json
  package.json
Labels: no-changelog

#114 Updating minimum version of python to 3.8
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  dev_requirements.in
  dev_requirements.txt
  noxfile.py
  requirements.in
  requirements.txt
  runtime.txt
  src/common/python.ts
  src/extension.ts
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#123 Clear diagnostic results on documents
  bundled/tool/lsp_server.py
  src/test/python_tests/test_data/sample1/sample3.py
  src/test/python_tests/test_linting.py
Labels: bug

#131 Handle diagnostic clean up
  bundled/tool/lsp_server.py
  src/common/settings.ts
  src/test/python_tests/test_linting.py
Labels: bug
