Repository microsoft/vscode-mypy, pull requests merged in 2023-09, with the labels that each got.

#141 Fix errors not don't clearing up after being fixed (#130, #139)
  bundled/tool/lsp_server.py
Labels: bug

#143 Introduce `preferDaemon` option in order to use non-daemon mypy on purpose
  README.md
  bundled/tool/lsp_server.py
  noxfile.py
  package.json
  package.nls.json
  src/common/settings.ts
  src/test/python_tests/test_non_daemon.py
Labels: feature-request

#151 Import bundled `packaging` after path munging
  bundled/tool/lsp_server.py
Labels: bug

#150 Update packages and requirements
  README.md
  dev_requirements.txt
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#149 Remove legacy path support
  src/common/settings.ts
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: debt

#152 Fix documentation and setting tags
  .vscode/settings.json
  README.md
  package.json
Labels: debt

#162 Added 3.12-dev python to test pipelines
  .github/workflows/pr-check.yml
Labels: debt, ghc-osd

#159 Capitalize instances of "python" in user-facing text
  README.md
  package.nls.json
Labels: debt, ghc-osd
