Repository microsoft/vscode-mypy, pull requests merged in 2023-11, with the labels that each got.

#195 Add more details to README and settings descriptions
  README.md
  package.nls.json
Labels: documentation, debt

#194 Update version and packages for release
  dev_requirements.txt
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#205 Update packages and version for pre-release
  dev_requirements.txt
  package-lock.json
  package.json
Labels: no-changelog

#209 Clean Up `README.md`
  README.md
Labels: bug, documentation

#215 Fix for `${fileDirname}` crash
  src/common/server.ts
Labels: bug

#218 Update Mypy settings descriptions
  README.md
  package.json
  package.nls.json
Labels: documentation, debt

#220 Use fnmatch instead of pathlibs match
  bundled/tool/lsp_utils.py
Labels: bug
