Repository microsoft/vscode-mypy, pull requests merged in 2023-06, with the labels that each got.

#36 Migrate to node16 and fix from other extensions
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
  package-lock.json
  package.json
  requirements.txt
  src/common/settings.ts
  src/test/python_tests/requirements.txt
Labels: no-changelog

#33 Update setting names in README
  README.md
Labels: bug

#32 Remove incorrect note from README
  README.md
Labels: bug

#51 Update packages and mypy
  README.md
  dev_requirements.txt
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#52 Switch to `dmypy`
  README.md
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  noxfile.py
  package.json
  src/common/logging.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/status.ts
  src/common/utilities.ts
  src/common/vscodeapi.ts
  src/extension.ts
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/test_extra_paths.py
  src/test/python_tests/test_linting.py
  src/test/python_tests/test_path_specialization.py
Labels: bug

#60 Engineering - add TSAOptions
  build/azure-pipeline.stable.yml
Labels: no-changelog

#58 Link to mypy's error code documentation
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  src/test/python_tests/test_linting.py
Labels: feature-request

#64 Fix off-by-one error with end column
  bundled/tool/lsp_server.py
  src/test/python_tests/test_linting.py
Labels: bug

#65 Add support for mypy `note`s
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  src/test/python_tests/test_data/sample1/sample.py
  src/test/python_tests/test_linting.py
Labels: feature-request

#68 Mark virtual workspaces as unsupported in package.json
  package.json
Labels: bug
