Repository microsoft/vscode-mypy, pull requests merged in 2024-09, with the labels that each got.

#321 Update packages for release
  README.md
  dev_requirements.txt
  package-lock.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#322 bump-release 2024.0.0
  package-lock.json
  package.json
Labels: no-changelog

#323 switch main to 2024.1 dev
  package-lock.json
  package.json
Labels: no-changelog

#256 Avoid resolving symlinks in `workspace` scope
  bundled/tool/lsp_utils.py
Labels: bug

#316 run mypy in the directory of the nearest pyproject.toml or mypy.ini
  README.md
  bundled/tool/lsp_server.py
  package.nls.json
  src/common/server.ts
Labels: feature-request
