Repository microsoft/vscode-mypy, pull requests merged in 2025-02, with the labels that each got.

#340 Update packages for final python 3.8 release
  README.md
  dev_requirements.txt
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: debt

#341 update version to 2025.1.0-dev
  package-lock.json
  package.json
Labels: no-changelog

#342 use correct capitalization of file paths to work around mypy issue
  bundled/tool/lsp_server.py
Labels: bug

#344 update capitalization of cwd to match file path
  bundled/tool/lsp_server.py
Labels: bug

#346 fix: bug where successive python changed events trigger creating multiple servers
  bundled/tool/lsp_server.py
  src/common/constants.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/utilities.ts
  src/extension.ts
Labels: bug

#349 chore: update minimum python to 3.9
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  dev_requirements.in
  dev_requirements.txt
  noxfile.py
  requirements.in
  requirements.txt
  runtime.txt
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
Labels: bug

#347 Add dmypy status file setting
  README.md
  bundled/tool/lsp_server.py
  package.json
  package.nls.json
  src/common/settings.ts
Labels: feature-request
