Repository microsoft/vscode-mypy, pull requests merged in 2025-03, with the labels that each got.

#350 bump to 2025.2.0
  package-lock.json
  package.json
Labels: no-changelog

#351 bump to 2025.3.0
  package-lock.json
  package.json
Labels: no-changelog

#352 Report only files specified by mypy config
  README.md
  bundled/tool/lsp_server.py
  package.json
  package.nls.json
  src/test/python_tests/test_data/pyproject.toml
  src/test/python_tests/test_linting.py
Labels: feature-request

#355 fix: syntax error in settings example
  package.nls.json
Labels: bug
